import type { Metadata } from "next";
import PageHeader from "@/components/PageHeader";
import SongLibrary from "@/components/SongLibrary";
import { getTrending } from "@/lib/youtube";

export const metadata: Metadata = { title: "Trending — Song Roulette" };

const FALLBACK_TEXT = {
  "no-key": "Live trending isn't configured. Showing a curated list of popular songs.",
  error: "Trending songs are temporarily unavailable. Showing a curated list instead.",
} as const;

export default async function TrendingPage() {
  const { songs, status, fetchedAt } = await getTrending();

  // The site is static: the list is regenerated by a scheduled GitHub Actions build,
  // so we show when it was generated rather than claiming "realtime".
  const subtitle =
    status === "live"
      ? `Updated ${new Date(fetchedAt).toLocaleString("vi-VN", {
          timeZone: "Asia/Ho_Chi_Minh",
          dateStyle: "short",
          timeStyle: "short",
        })} · refreshed about once an hour`
      : FALLBACK_TEXT[status];

  return (
    <div className="mx-auto w-full max-w-6xl px-5 py-8 sm:px-8 sm:py-14">
      <PageHeader eyebrow="Trending" title={"What's hot right now."} subtitle={subtitle} />
      <SongLibrary songs={songs} languages />
    </div>
  );
}
